"use client"

import Image from "next/image"
import Link from "next/link"
import { cn } from "@/lib/utils"

interface LogoProps {
  className?: string
  asLink?: boolean
  size?: number
  priority?: boolean
}

// Prefers SVG (crisp, scalable). Falls back to PNG if SVG missing.
export function Logo({ className, asLink = true, size = 48, priority = false }: LogoProps) {
  const img = (
    <picture>
      {/* Future: AVIF/WebP sources generated by optimize script */}
      <source srcSet="/logo-awe.svg" type="image/svg+xml" />
      <Image
        src="/logo-awe.png"
        alt="Logo AgroWomanEcology"
        width={size}
        height={size}
        priority={priority}
        className={cn("object-contain select-none", className)}
      />
    </picture>
  )
  if (!asLink) return img
  return (
    <Link href="/" aria-label="Accueil AgroWomanEcology" className="flex items-center gap-3 group">
      {img}
      <span className="text-xl font-serif font-bold leading-tight">
        <span className="block">AgroWoman</span>
        <span className="text-primary">Ecology</span>
      </span>
    </Link>
  )
}
